### ISSUE TITLE
[BUG] Unable to login for non IDP users

### ISSUE THREAD

**Issue by anuragpathak21** [sventorben/keycloak-home-idp-discovery#263] opened 2023-10-31 12:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://github.com/sventorben/keycloak-home-idp-discovery/releases/tag/v22.1.0

Trying to login using user who is not associated to any IDP and the user's email Domain is also not configured for any IDP. Getting invalid username password error.

Log
```
WARN  [org.keycloak.events] (executor-thread-10) type=LOGIN_ERROR, realmId=test-realm, clientId=test, userId=null, ipAddress=172.29.0.1, error=invalid_user_credentials, auth_method=openid-connect, auth_type=code, redirect_uri=https://www.keycloak.org/app/#url=http://localhost:8080&realm=test-realm&client=test, code_id=9686cabf-e99e-45cf-b9a4-94d7c2fd811c, username=tpmuser@gmail.com
INFO  [de.sventorben.keycloak.authentication.hidpd.HomeIdpDiscoverer] (executor-thread-14) Could not find home IdP for domain 'gmail.com' and user 'tpmuser@gmail.com' in realm 'test-realm'
```

### Expected Behavior

If the user's email's domian is not configured for any IDP as home.idp.discovery.domains then it should display password form to let user login using password from Keycloak

### Version

```markdown
- Keycloak:22.0.5
- This extension:22.1.0
```

### Anything else?

<img width="1389" alt="image" src="https://github.com/sventorben/keycloak-home-idp-discovery/assets/50142570/fafd947e-1693-4555-82d4-9a7f87005bbc">

<img width="1366" alt="image" src="https://github.com/sventorben/keycloak-home-idp-discovery/assets/50142570/95d222bf-736c-4e8f-a023-b2993b9999e6">

<img width="1309" alt="image" src="https://github.com/sventorben/keycloak-home-idp-discovery/assets/50142570/b2a458ea-de9b-4630-adcd-e92e5bbc778a">

<img width="627" alt="image" src="https://github.com/sventorben/keycloak-home-idp-discovery/assets/50142570/ddffa7c8-f114-4e95-8718-c9d25c58a7dd">

<img width="592" alt="image" src="https://github.com/sventorben/keycloak-home-idp-discovery/assets/50142570/230898f5-321d-4379-94ae-019f731f01ea">

<img width="573" alt="image" src="https://github.com/sventorben/keycloak-home-idp-discovery/assets/50142570/96b1723b-e253-43a5-a079-51ae5df3177d">

**Comment by sventorben** [comment] 2023-10-31 14:41
Hello @anuragpathak21,

this may be caused by the breaking change mentioned in the release notes. Please see #251 for details.
In you use case, you may want to try to change your alternative authenticator from "Password Form" to "Username Password Form" as [shown in the docs](https://sventorben.github.io/keycloak-home-idp-discovery/configuration.html).

Please let me know if this helps.

Sven-Torben

**Comment by anuragpathak21** [comment] 2023-11-01 02:03
After adding Username Password Form to Authentication flow (see attached image) following the docs, Auto IDP discovery is not working and it's always taking to username password form.
I will appreciate of you can validate if our expectation aligns with the plugin behaviour or highlight any gaps.

- User will be presented with username field and direct IDP buttons (Working as expected)
- User enters the username/email in the username field and clicks on Sign In
- KC identifies if the user's email is associateed to any IDP based on the domain 
-  If the user's domain is not associated to any domain then redirect to password form, hwere user can enter the password and continue to loigin
-  If the user's domain is associated to any IDP or his/her domain is configured with and IDP then redirect to IDP page.

Additional points:

- User associated with IDM or domain configured with IDP should not be allowed to use Reset Password functionality of KC.



<img width="1361" alt="image" src="https://github.com/sventorben/keycloak-home-idp-discovery/assets/50142570/91ad19b7-8538-44ce-a6be-9379fd2e9756">

<img width="547" alt="image" src="https://github.com/sventorben/keycloak-home-idp-discovery/assets/50142570/80ac4353-e9b0-492b-b978-23f0df83d723">

**Comment by sventorben** [comment] 2023-11-01 10:10
> After adding Username Password Form to Authentication flow (see attached image) following the docs, Auto IDP discovery is not working and it's always taking to username password form.

There is an integration test for you scenario, so I assume that something in your config is not set up as needed. Can you share an export of your realm configuration?
Or increase the log level and share the logs (see [FAQ](https://sventorben.github.io/keycloak-home-idp-discovery/faq.html#user-is-not-redirected-to-the-correct-identity-provider-how-to-analyze-the-problem) for details)

> * User will be presented with username field and direct IDP buttons (Working as expected)
> * User enters the username/email in the username field and clicks on Sign In
> * KC identifies if the user's email is associateed to any IDP based on the domain
> * If the user's domain is not associated to any domain then redirect to password form, hwere user can enter the password and continue to loigin

yes, this is how it is expected to work.

> * If the user's domain is associated to any IDP or his/her domain is configured with and IDP then redirect to IDP page.

Yes, that is correct. However, it depends on the details of the configuration when the user will be redirected or not. Have you checked that the email of the user is marked as verified?

> * User associated with IDM or domain configured with IDP should not be allowed to use Reset Password functionality of KC.

This is out of the scope of this extension for now and currently not supported.

**Comment by punjasolanki** [comment] 2023-11-01 16:21
@anuragpathak21 @sventorben Seems like there's an issue with the latest version. I was facing the same issue with the latest version, I downgraded the version to v22.0.0 and it behaves correctly.

**Comment by sventorben** [comment] 2023-11-01 16:46
@punjasolanki can you provide logs and your configuration, please?

**Comment by anuragpathak21** [comment] 2023-11-02 01:14
Please find attached log
[kc-idp-home-log1.txt](https://github.com/sventorben/keycloak-home-idp-discovery/files/13233091/kc-idp-home-log1.txt)

**Comment by sventorben** [comment] 2023-11-02 03:54
Thanks, @anuragpathak21. 
As far as I can see from that log, the authenticator could not find the home IdP for the user. I think that this is the correct behavior in your scenario.

Can you please export your realm configuration and share it here, so I can try to reproduce and debug that issue?

**Comment by anuragpathak21** [comment] 2023-11-02 06:17
It's the realm config found in this repo. I have attached it with the comment.
[test-realm.json](https://github.com/sventorben/keycloak-home-idp-discovery/files/13234958/test-realm.json)

**Comment by sventorben** [comment] 2023-11-02 15:59
@anuragpathak21 The flow in that JSON file looks like this.

![image](https://github.com/sventorben/keycloak-home-idp-discovery/assets/12183470/17631a59-5b6c-44b4-844f-ce39996851ae)

That flow requires the Home IdP Discovery authenticator. If the user cannot be redirected, authentication fails, because there is no alternative configured. Please see the [documentation](https://sventorben.github.io/keycloak-home-idp-discovery/configuration.html#authenticator-execution) to configure a flow with username & password as an alternative.

**Closed by sventorben** 2023-11-02 15:59 UTC
Labels: bug
