### ISSUE TITLE
Logging in with username password

### ISSUE THREAD

**Issue by torvalde** [sventorben/keycloak-home-idp-discovery#74] opened 2022-06-24 13:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a user that I have configured in keycloak with username/password

I try to login with the default auth flow (browser) and it works fine, but when I enable the new flow that includes home idp discovery I get the error message:

Invalid username or password

### Expected Behavior

I expect to get the chance to type in the password for the user and be logged in normally.

**Comment by torvalde** [comment] 2022-06-24 14:21
<img width="1482" alt="image" src="https://user-images.githubusercontent.com/386366/175555145-8f062575-4889-4f75-82ca-2a7be39b904e.png">

<img width="991" alt="image" src="https://user-images.githubusercontent.com/386366/175555288-c0cb11ed-fbbb-44bb-8992-cf240fbdef51.png">

**Comment by sventorben** [comment] 2022-06-24 14:28
Closing this issue, since it is not a bug with this authenticator but a configuration issue.

**Comment by torvalde** [comment] 2022-06-24 14:29
Thank you for your help, sorry for the trouble.

**Closed by sventorben** 2022-06-24 14:28 UTC
Labels: bug
